import enum
from .types import LN
from typing import Any

class InferredType(enum.IntEnum):
    UNSET: int = ...
    BOOL: int = ...
    INT: int = ...
    INT_OR_FLOAT: int = ...
    FLOAT: int = ...
    COMPLEX: int = ...
    UNKNOWN: int = ...

def numeric_expr_type(
    node: LN, use_py2_division: Any = ..., type_for_unknown: InferredType = ...
) -> InferredType: ...
