# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - libdbus-1-dev
    - libgirepository1.0-dev
    - gir1.2-gtk-3.0
    - gir1.2-notify-0.7
    - gir1.2-gudev-1.0
    - graphviz
    - imagemagick
    - xserver-xephyr
    - xvfb
    - dbus-x11
    - libnotify-bin
# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
# Optionally build your docs in additional formats such as PDF
formats:
- pdf
- htmlzip
- epub
# Optionally set the version of Python and requirements required to build your docs
python:
  install:
  # This first requirements file installs a pinned version of cffi as latest version causes crashes
  - requirements: docs/requirements-rtd.txt
