#!/usr/bin/env python

import os, os.path
import libqtile
import libqtile
import libqtile.sh as sh

def main():
    from optparse import OptionParser, OptionGroup
    parser = OptionParser(version="%prog 0.1")
    parser.add_option(
                        "-c", "--config",
                        action="store", type="string",
                        default=None,
                        dest="configfile",
                        help='Use specified configuration file.'
                    )
    parser.add_option(
                        "-s", "--socket",
                        action="store", type="string",
                        default=None,
                        dest="socket",
                        help='Use specified communication socket.'
                    )
    options, args = parser.parse_args()

    try:
        c = libqtile.config.File(options.configfile)
    except libqtile.config.ConfigError, v:
        parser.error(v.message)
    client = libqtile.command.Client(options.socket, c)
    cmd = sh.Cmd(client)
    cmd.cmdloop()


if __name__ == "__main__":
    main()


