#!/usr/bin/env python

import os, os.path
import libqtile
import libqtile.config as config

def main():
    from optparse import OptionParser, OptionGroup
    parser = OptionParser(version="%prog 0.1")
    parser.add_option(
                        "-c", "--config",
                        action="store", type="string",
                        dest="configfile",
                        help='Use specified configuration file.'
                    )
    options, args = parser.parse_args()

    configfile = options.configfile
    if not configfile:
        configfile = os.path.join("~", ".qtile", "config.py")
        configfile = os.path.expanduser(configfile)
    try:
        c = config.File(configfile)
    except config.ConfigError, v:
        parser.error(v.message)

    d = os.environ["DISPLAY"]
    fname = os.path.join("~", ".qtilesocket.%s"%d)
    fname = os.path.expanduser(fname)
    if os.path.exists(fname):
        os.unlink(fname)
    q = libqtile.QTile(c, d, fname)
    q.loop()


if __name__ == "__main__":
    main()

