#!/usr/bin/env python

import os, os.path
import libqtile
import libqtile.config as config

def main():
    from optparse import OptionParser, OptionGroup
    parser = OptionParser(version="%prog 0.1")
    parser.add_option(
                        "-c", "--config",
                        action="store", type="string",
                        default=None,
                        dest="configfile",
                        help='Use specified configuration file.'
                    )
    parser.add_option(
                        "-d", "--debug",
                        action="store_true", default=False,
                        dest="debug",
                        help='Print lots of debugging output.'
                    )
    options, args = parser.parse_args()

    try:
        c = config.File(options.configfile)
    except config.ConfigError, v:
        parser.error(v.message)
    d = os.environ.get("DISPLAY")
    if not d:
        parser.error("No DISPLAY set.")
    fname = os.path.join("~", ".qtilesocket.%s"%d)
    fname = os.path.expanduser(fname)
    if os.path.exists(fname):
        os.unlink(fname)
    q = libqtile.QTile(c, d, fname)
    q.debug = options.debug
    q.loop()


if __name__ == "__main__":
    main()
