from typing import Any

class ImageLoadingError(ValueError): ...

class Pixbuf:
    def __init__(self, pointer: Any) -> None: ...
    def __getattr__(self, name: Any): ...

def decode_to_image_surface(
    image_data: Any, width: Any | None = ..., height: Any | None = ...
): ...
