from typing import Any, Optional

class ImageLoadingError(ValueError): ...

class Pixbuf:
    def __init__(self, pointer: Any) -> None: ...
    def __getattr__(self, name: Any): ...

def decode_to_image_surface(
    image_data: Any, width: Optional[Any] = ..., height: Optional[Any] = ...
): ...
