from groupbox import GroupBox
from groupbox import AGroupBox
from windowname import WindowName
from textbox import TextBox
from spacer import Spacer
from clock import Clock
from mpdwidget import Mpd
from sep import Sep
from prompt import Prompt
from systray import Systray
from graph import *
