name: "Report an issue"
description: "Our tracker for bugs and other issues with the core project"
labels: ["unconfirmed"]
body:
  - type: markdown
    attributes:
     value: |
       Please note that this tracker is only for bugs or other issues with the core project.
  - type: markdown
    attributes:
     value: |
       Please include:
       - Your Qtile version (`qtile --version`).
       - Relevant **logs** from `~/.local/share/qtile/qtile.log`.
       - If relevant, the problematic part of your config.
  - type: textarea
    attributes:
      label: "The issue:"
      value: I wanted to do X, but Y happened, and I expected Z. I think this is a bug.
    validations:
      render: markdown
  - type: checkboxes
    attributes:
      label: "Required:"
      options:
        - label: I have searched past issues to see if this bug has already been reported.
          required: true
