---
name: Bug Report
about: Please note that this tracker is only for bugs or other issues with the core project.
title: ''
labels: 'unconfirmed, bug'
assignees: ''

---

**Metadata (please complete the following information)**
- Your Qtile version (`qtile --version`).
- Relevant **logs** from `~/.local/share/qtile/qtile.log`.
- If relevant, the problematic part of your config.

**Describe the bug
I wanted to do X, but Y happened, and I expected Z. I think this is a bug.

**Additional context**
I have searched past issues to see if this bug has already been reported.

**footer**
Have a **general question**?
There are [community contact](https://github.com/qtile/qtile#community) options for that, or ask at [Q&A](https://github.com/qtile/qtile/discussions/categories/q-a).

Have a **feature idea**?
Please post it on the discussions board as an [idea](https://github.com/qtile/qtile/discussions/categories/ideas).
