from stack import Stack
from max import Max
from xmonad import MonadTall
from tile import Tile
from floating import Floating
from ratiotile import RatioTile
from slice import Slice
from tree import TreeTab
from zoomy import Zoomy
