#!/usr/bin/env bash
set -euo pipefail

source "$(dirname "$0")/ci-env"

[ "$(grep -c -P '\t' CHANGELOG)" = "0" ]

make \
  QTILE_CI_PYTHON="${QTILE_CI_PYTHON}" \
  QTILE_CI_BACKEND="${QTILE_CI_BACKEND}" \
  check check-packaging

uv run coverage combine -q
uv run coverage report -m
uv run coverage xml

# Upload to coveralls
uv tool run coveralls --service=github || true
