#!/bin/sh
echo "building pango"
python3 ./libqtile/pango_ffi_build.py
echo "building xcursors"
python3 ./libqtile/backend/x11/xcursors_ffi_build.py
echo "building pulseaudio volume control"
python3 ./libqtile/widget/pulseaudio_ffi.py
