#!/usr/bin/env python
"""
    Command-line interaction with Qtile TextBox widgets.
"""
import os, sys
from optparse import OptionParser, OptionGroup
from libqtile import confreader, command

def main():
    parser = OptionParser(
                usage="%prog [options] name text",
                version="%prog 0.2",
            )
    parser.add_option("-l", "--list",
                      action="store_true", dest="list",
                      help="List addressible widgets.")
    parser.add_option(
                        "-c", "--config",
                        action="store", type="string",
                        default=None,
                        dest="configfile",
                        help='Use specified configuration file.'
                    )
    parser.add_option(
                        "-s", "--socket",
                        action="store", type="string",
                        default=None,
                        dest="socket",
                        help='Use specified communication socket.'
                    )
    (options, args) = parser.parse_args()
    try:
        c = confreader.File(options.configfile)
    except confreader.ConfigError, v:
        parser.error(v.message)

    client = command.Client(options.socket, c)

    if options.list:
        for i in client.list_widgets():
            print i
    else:
        if len(args) < 2:
            parser.error("Please specify widget name and argument.")
        try:
            client.widget.__getitem__(args[0]).update(" ".join(args[1:]))
        except command.CommandError, v:
            print >> sys.stderr, v
            sys.exit(1)


if __name__ == "__main__":
    main()
