#!/usr/bin/env bash
#
# Helper script to install the non-Python Wayland dependencies on Ubuntu. This
# is required because most of the time the wlroots version we depend on is more
# recent than that which can be found in the Ubuntu package repository. This
# script is used for CI on GitHub and the ReadTheDocs environment.

set -e

# The versions we want
WAYLAND=1.21.0
WAYLAND_PROTOCOLS=1.31
WLROOTS=0.16.0
SEATD=0.7.0
LIBDRM=2.4.114

# Build wayland
wget -q --no-check-certificate https://wayland.freedesktop.org/releases/wayland-$WAYLAND.tar.xz
tar -xJf wayland-$WAYLAND.tar.xz
cd wayland-$WAYLAND
meson build -Ddocumentation=false --prefix=/usr
ninja -C build
sudo ninja -C build install
cd ../

# Build wayland-protocols
wget -q --no-check-certificate https://wayland.freedesktop.org/releases/wayland-protocols-$WAYLAND_PROTOCOLS.tar.xz
tar -xJf wayland-protocols-$WAYLAND_PROTOCOLS.tar.xz
cd wayland-protocols-$WAYLAND_PROTOCOLS
meson build -Dtests=false --prefix=/usr
ninja -C build
sudo ninja -C build install
cd ../

# Build seatd
wget -q --no-check-certificate https://git.sr.ht/~kennylevinsen/seatd/archive/$SEATD.tar.gz
tar -xzf $SEATD.tar.gz
cd seatd-$SEATD
meson build --prefix=/usr
ninja -C build
sudo ninja -C build install
cd ../

# Build libdrm
wget -q --no-check-certificate https://gitlab.freedesktop.org/mesa/drm/-/archive/libdrm-$LIBDRM/drm-libdrm-$LIBDRM.tar.gz
tar -xzf drm-libdrm-$LIBDRM.tar.gz
cd drm-libdrm-$LIBDRM
meson build --prefix=/usr
ninja -C build
sudo ninja -C build install
cd ../

# Build wlroots
wget -q --no-check-certificate https://gitlab.freedesktop.org/wlroots/wlroots/-/archive/$WLROOTS/wlroots-$WLROOTS.tar.gz
tar -xzf wlroots-$WLROOTS.tar.gz
cd wlroots-$WLROOTS
meson build -Dexamples=false --prefix=/usr -Dxwayland=enabled
ninja -C build
sudo ninja -C build install
cd ../
