#!/usr/bin/env python
import sys, time
from Xlib import display, error, X

for i in range(20):
    try:
        d = display.Display(sys.argv[1])
    except error.DisplayConnectionError:
        time.sleep(0.1)
        continue
    break
else:
    print >> sys.stderr, "Could not open window on display %s"%(sys.argv[1])
    sys.exit(1)

root = d.screen().root
colormap = d.screen().default_colormap
background = colormap.alloc_named_color("blue").pixel
window = root.create_window(100, 100, 100, 100, 1,
                            X.CopyFromParent, X.InputOutput,
                            X.CopyFromParent,
                            background_pixel = background,
                            event_mask = X.StructureNotifyMask | X.ExposureMask)
window.set_wm_name(sys.argv[2])
window.map()
while 1:
    event = d.next_event()
