class AccessError: ...

class ClientMessageEvent: ...

class ClientMessageData: ...

class ConfigWindow: ...

class CreateNotifyEvent: ...

class CW: ...

class DrawableError: ...

class EventMask:
    KeyPress = ...  # type: int
    ButtonPress = ...  # type: int
    ButtonRelease = ...  # type: int
    EnterWindow = ...  # type: int
    Exposure = ...  # type: int
    StructureNotify = ...  # type: int
    FocusChange = ...  # type: int
    PropertyChange = ...  # type: int

class FocusInEvent: ...

class FocusOutEvent: ...

class KeyReleaseEvent: ...

class LeaveNotifyEvent: ...

class MapNotifyEvent: ...

class NoExposureEvent: ...

class ReparentNotifyEvent: ...

class SetMode: ...

class StackMode: ...

class WindowClass: ...

class WindowError: ...
