name: ci

on:
    push:
    pull_request:

jobs:
    tests:
        runs-on: ubuntu-24.04
        name: "python ${{ matrix.python-version }} on ${{ matrix.backend }}"
        strategy:
            matrix:
                python-version: ['3.12', '3.13', '3.14']
                backend: ['x11', 'wayland']
        steps:
            - uses: actions/checkout@v6

            - name: Build Docker image
              run: docker build -t qtile-ci:local .

            - name: Run tests in container
              run: |
                docker run --rm \
                  -v ${{ github.workspace }}:/workspace \
                  -e USER_UID=`id -u` -e USER_GID=`id -g` \
                  -e QTILE_CI_PYTHON=${{ matrix.python-version }} \
                  -e QTILE_CI_BACKEND=${{ matrix.backend }} \
                  -e GITHUB_ACTIONS=true \
                  -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
                  -e GITHUB_REF=${{ github.ref }} \
                  -e GITHUB_SHA=${{ github.sha }} \
                  -e COVERALLS_FLAG_NAME=${{ format('{0}-{1}', matrix.python-version, matrix.backend) }} \
                  -e COVERALLS_PARALLEL=true \
                  -e COVERALLS_SERVICE_JOB_ID=${{ github.run_id }} \
                  qtile-ci:local \
                  /workspace/scripts/ci-run-test

    coverage:
        name: Finalize Coverage
        needs: tests
        runs-on: ubuntu-24.04
        steps:
            - name: Coveralls Finished
              uses: coverallsapp/github-action@main
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                parallel-finished: true
